=== hindanjali/Ontology-for-food-delivery-system/dtd_file.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE food_delivery_system[
<!ELEMENT food_delivery_system (orders, users, restaurants)>
<!ELEMENT users (user)>
<!ELEMENT restaurants (restaurant)>
<!ELEMENT orders (order)>
<!ELEMENT order (customer, delivery,food,bill)>
<!ATTLIST order order_id ID #REQUIRED>
<!ELEMENT customer (name,address,contact_number,email)>
<!ATTLIST customer user_id ID #REQUIRED>
<!ELEMENT delivery(delivery_boy)>
<!ELEMENT food (food_item+)>
<!ATTLIST restaurant_id ID #REQUIRED>
<!ELEMENT bill (amount,payment)>
<!ATTLIST bill bill_number ID #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (locality,city,pincode)>
<!ELEMENT contact_number (NUMBER)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT delivery_boy (name,contact_number,rating)>
<!ATTLIST delivery_boy user_id ID #REQUIRED>
<!ELEMENT food_item (name,quantity,price)>
<!ELEMENT user EMPTY >
<!ATTLIST user user_id ID #REQUIRED user_type(customer|delivery_boy) >
<!ELEMENT price (NUMBER)>
<!ELEMENT restaurant (name,menu,feedback,address)>
<!ATTLIST restaurant_id ID #REQUIRED>
<!ELEMENT amount (NUMBER)>
<!ELEMENT payment EMPTY>
<!ELEMENT rating (NUMBER)>
<!ELEMENT quantity (NUMBER)>
<!ELEMENT menu (menu_item) >
<!ELEMENT feedback (#PCDATA)>
<!ELEMENT payment EMPTY >
<!ATTLIST payment mode (online|COD) status(paid|pending)>
<!ELEMENT menu_item (name,price) >
<!ELEMENT locality (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT pincode (NUMBER)>
]>

=== hindanjali/Ontology-for-food-delivery-system/Untitled1.xml
<?xml version="1.0"?>
<!DOCTYPE food_delivery_system SYSTEM "dtd_file.dtd">
<food_delivery_system>
    <orders>
        <order order_id="o501">
            <customer user_id="shashank101">
                <name> Shashank</name>
                <address> 
                    <locality> abajan apartment </locality>
                    <city>surat</city>
                    <pincode>395900</pincode>
                </address>
                <contact_number>9123459775</contact_number>
                <email> shashank@gmail.com</email>
            </customer>
            <delivery>
                <delivery_boy user_id="rohit434">
                    <name>rohit</name>
                    <contact> 9856234597</contact>
                    <rating> 5 </rating>
                </delivery_boy>     
            </delivery>
            <food restaurant_id="rest123">
                <food_item>
                    <name> dosa </name>
                    <quantity> 1</quantity>
                    <price> 80 </price>
                </food_item>
                <food_item>
                    <name> uttapam </name>
                    <quantity> 2 </quantity>
                    <price> 100 </price>
                </food_item>
            </food>
            <bill bill_number="b7019">
                <amount> 280 </amount>
                <payment mode="online" status="paid" />
            </bill>
        </order>
    </orders>
    <users>
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
        <user user_id="" user_type="" />
    </users>
    <restaurants>
        <restaurant>
            <name> </name>
            <menu>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
            </menu>
            <feedback> </feedback>
            <address>
                <locality>  </locality>
                <city> </city>
                <pincode> </pincode>
            </address>
        </restaurant>
        <restaurant>
            <name> </name>
            <menu>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
            </menu>
            <feedback> </feedback>
            <address>
                <locality>  </locality>
                <city> </city>
                <pincode> </pincode>
            </address>
        </restaurant>
        <restaurant>
            <name> </name>
            <menu>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
            </menu>
            <feedback> </feedback>
            <address>
                <locality>  </locality>
                <city> </city>
                <pincode> </pincode>
            </address>
        </restaurant>
        <restaurant>
            <name> </name>
            <menu>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
            </menu>
            <feedback> </feedback>
            <address>
                <locality>  </locality>
                <city> </city>
                <pincode> </pincode>
            </address>
        </restaurant>
        <restaurant>
            <name> </name>
            <menu>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
                <menu_item>
                    <name> </name>
                    <price> </price>
                </menu_item>
            </menu>
            <feedback> </feedback>
            <address>
                <locality>  </locality>
                <city> </city>
                <pincode> </pincode>
            </address>
        </restaurant>
    </restaurants>
    
</food_delivery_system>
